web:
  build: .
  ports:
  - "8800:3000"
  - "56745:56745"
  volumes:
  - .:/usr/src/app/:rw
  environment:
  - NODE_ENV=dev
  command: >
    sh -c '
      if test -d node_modules; 
      then 
        echo node_modules_exists ; 
      else 
        cp -a /tmp/node_modules /usr/src/app/website; 
      fi && 
      npm install && 
      /usr/local/bin/node --inspect ./index.js
    '